apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xfyxiqspe-nodejs 
  janus-idp.io/tekton: xfyxiqspe-nodejs
  backstage.io/kubernetes-id: xfyxiqspe-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xfyxiqspe-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml